### PR TITLE
Update sample

### PR DESCRIPTION
**Pull request by shirhatti**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
nit: this wont work until we update the vcpkg port

**Comment by BrennanConroy** [comment]
https://github.com/microsoft/vcpkg/pull/16885

**Comment by halter73** [comment]
It's not longer `-D CMAKE_PREFIX_PATH="C:/dev/microsoft/vcpkg/installed/x64-windows/"`, right? What do we use now? I want to keep the README steps up-to-date.

**Comment by BrennanConroy** [comment]
`-DCMAKE_TOOLCHAIN_FILE=<path to vcpkg\scripts\buildsystems\vcpkg.cmake>`

**Comment by halter73** [comment]
That worked!

**Comment by halter73** [comment]
Thanks @shirhatti

**Pull request merged**
